[azure]
form_recognizer_endpoint = "https://ai-aihackthonhub282549186415.cognitiveservices.azure.com/"
form_recognizer_key = "Fj1KPt7grC6bAkNja7daZUstpP8wZTXsV6Zjr2FOxkO7wsBQ5SzQJQQJ99BCACHYHv6XJ3w3AAAAACOGL3Xg"
form_recognizer_api_version = "2024-02-29-preview"

openai_endpoint = "https://ai-aihackthonhub282549186415.openai.azure.com"
openai_key = "Fj1KPt7grC6bAkNja7daZUstpP8wZTXsV6Zjr2FOxkO7wsBQ5SzQJQQJ99BCACHYHv6XJ3w3AAAAACOGL3Xg"
openai_deployment = "gpt-4"
openai_api_version = "2024-02-15-preview"

computer_vision_endpoint = "https://ai-aihackthonhub282549186415.cognitiveservices.azure.com/"
computer_vision_key = "Fj1KPt7grC6bAkNja7daZUstpP8wZTXsV6Zjr2FOxkO7wsBQ5SzQJQQJ99BCACHYHv6XJ3w3AAAAACOGL3Xg"

language_endpoint = "https://ai-aihackthonhub282549186415.cognitiveservices.azure.com/"
language_key = "Fj1KPt7grC6bAkNja7daZUstpP8wZTXsV6Zjr2FOxkO7wsBQ5SzQJQQJ99BCACHYHv6XJ3w3AAAAACOGL3Xg"
